version: 0.0
os: linux
runas: ubuntu

files:
  - source: /
    destination: /home/ubuntu/nodejs/*
    overwrite: true
    timeout: 500
    
hooks:
  BeforeInstall:
    - location: /home/ubuntu/nodejs/script/install.sh
      timeout: 300
      runas: root


  ApplicationStop:
    - location: /home/ubuntu/nodejs/script/stop.sh
      timeout: 300
      #runas: root


  ApplicationStart:
    - location: /home/ubuntu/nodejs/script/start.sh
      timeout: 300
      #runas: root
